### ISSUE TITLE
How to get the video stream from Insta360?

### ISSUE THREAD

**Issue by KennethYangle** [tu-darmstadt-ros-pkg/image_projection#1]
Hi,

I am interested in using this project with my research. However, I would like to know how to get the video stream of Insta360 Air in real-time and forward it to the topic `/camera360_nodelet_loader/compressed/image_raw`. Does this method support Insta360 ONE X2?

Thanks!

**Comment by Martin-Oehler** [comment]
Hello,
thank you for your interest.

The Insta360 Air is recognized as a UVC device when connected via USB, so you can use a standard camera driver like [libuvc_camera](http://wiki.ros.org/libuvc_camera) or [usb_cam](http://wiki.ros.org/usb_cam).  `/camera360_nodelet_loader/compressed/image_raw` is the compressed stream in the bag file which is unpacked to `/camera360/image_raw` [here](https://github.com/tu-darmstadt-ros-pkg/image_projection/blob/master/image_projection_demo/launch/rosbag.launch#L14). So `/camera360/image_raw` is the topic where the driver has to ouput the raw image.

The Insta360 Air transmits both lenses in a single image, so afterwards the image is split [here](https://github.com/tu-darmstadt-ros-pkg/image_projection/blob/master/image_projection_demo/launch/rosbag.launch#L19) to the topics `/camera360/left/image_raw`and `/camera360/right/image_raw`.

We have not tested the Insta360 ONE X2. Some cams support streaming modes for use as a webcam, sometimes over RTMP/RTSP. You can look for something like that. However, you have to make sure that you receive the original fisheye images, not some kind of stitched panorama.

**Comment by KennethYangle** [comment]
Thank you for your reply. When the Insta360 ONE X2 is used as a USB camera, it outputs corrected pinhole projection images. I prefer to stitch the original fisheye image into a spherical image. I will try the Insta360 Air later.
