### ISSUE TITLE
Invalid parameter "dist_between_cameras"

### ISSUE THREAD

**Issue by barabun** [tu-darmstadt-ros-pkg/image_projection#5]
Hi, 
Thank's a lot for the interesting project. I'm trying to run the demo example. Unfortunatelly when I run `roslaunch image_projection_demo demo_insta360.launch` I get this error 

```
Invalid parameter "dist_between_cameras"
when instantiating macro: camera360 (/opt/ros/melodic/share/hector_sensors_description/urdf/camera360.urdf.xacro)
in file: /home/tower/catkin_ds/src/image_projection/image_projection_demo/urdf/insta360.urdf.xacro
RLException: while processing /home/tower/catkin_ds/src/image_projection/image_projection_demo/launch/rosbag.launch:
while processing /home/tower/catkin_ds/src/image_projection/image_projection_demo/launch/tf.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/melodic/lib/xacro/xacro', '/home/tower/catkin_ds/src/image_projection/image_projection_demo/urdf/insta360.urdf.xacro']] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro $(find image_projection_demo)/urdf/insta360.urdf.xacro" name="robot_description"/>
The traceback for the exception was written to the log file
```
Could you please give me a hint, where the problem can be? 
Best regards,
Igor

**Comment by Martin-Oehler** [comment]
I guess, the version of hector_sensors_description distributed by the ros build farm is outdated, for some reason. Can you send me the output of `apt show ros-melodic-hector-sensors-description`?

In the meantime, you can check out the repository manually
```
roscd
git clone https://github.com/tu-darmstadt-ros-pkg/hector_models.git --branch melodic-devel
```

Best regards,
Martin

**Comment by StefanFabian** [comment]
> I guess, the version of hector_sensors_description distributed by the ros build farm is outdated, for some reason.

That reason is usually breaking changes which is normally also the reason why a new branch is created.
Since the release is tracking kinetic-devel, I assume the melodic branch was created after the package was already released.
I don't know what the changes are and if they include some breaking stuff that would not allow an upgrade to the newer version.
Also, since we're already on noetic, support for older distributions is kind of  limited.

**Comment by Martin-Oehler** [comment]
> I don't know what the changes are and if they include some breaking stuff that would not allow an upgrade to the newer version.

For the file in question, both branches are on the same state. The parameter causing the error has been added in 2018 (https://github.com/tu-darmstadt-ros-pkg/hector_models/commit/ff43c0a6a79b637f61bf1f53a9975b50bef347e7).

**Comment by IamPhytan** [comment]
Sorry for reopening this issue, but I have the exact same problem. I have a question on the proposed solution from @Martin-Oehler :

> ```
> roscd
> git clone https://github.com/tu-darmstadt-ros-pkg/hector_models.git --branch melodic-devel
> ```

`roscd` brings me to  `WS_DIR/devel`, so should the dependency instead be cloned inside `WS_DIR//src` ?

**Comment by Martin-Oehler** [comment]
Yes, that is correct.
